### PR TITLE
rpm spec: fix config file packaging

### PR DESCRIPTION
**Pull request by mbukatov**
This is a proposal of fix for https://github.com/Tendrl/common/issues/72, I haven't tried to build the package though.

### CODE REVIEW

**Comment by r0h4n** [comment]
Thanks for this, please format your commit msg as per https://github.com/Tendrl/common/issues/66

**Comment by mbukatov** [comment]
All right, I will do a rebase to fix the commit message.

**Comment by shtripat** [comment]
Looks good if commit message is formatted as suggested.

**Comment by r0h4n** [comment]
@mbukatov Please update with fixes

**Comment by mbukatov** [comment]
@r0h4n commit message has been rebased

**Pull request merged**
